image: node:22.14.0

before_script:
  - npm ci

pages:
  stage: deploy
  script:
    - npm run build
    - cp out/index.html out/404.html
  artifacts:
    paths:
      - out
  only:
    - main
    - master
